### ISSUE TITLE
How to use 'AND' or 'OR' operator in  findWhere

### ISSUE THREAD

**Issue by nahid** [SebastianBerc/Repositories#24]
I'm using this package for my project. I want to find an user where id=1 or username='username' but I can not do this. 

How can I do this?

**Comment by SebastianBerc** [comment]
I'll fix it.

**Comment by Stefanescul** [comment]
SELECT * FROM Customers
WHERE id='1'
AND username='username'; 
If you wanna select id=1 and username = with username
-----------------------------
SELECT * FROM Customers
WHERE id='1'
OR username='username';
Tell me if it's work.
