### ISSUE TITLE
Make a first release

### ISSUE THREAD

**Issue by tyloo** [SebastianBerc/Repositories#4]
Hello,

I'm starting to use your package, and the first advice for you would be to work on "releases" with at least version tagging. Put a tag v1.0.0 when you feel like it's stable enough (and I guess it is) ;) Thanks!

**Comment by tyloo** [comment]
Reason is taht Insight (https://insight.sensiolabs.com/) says taht it's not a good practice to put dev-master as a version on composer.

**Comment by SebastianBerc** [comment]
Hi tyloo, thanks for your message - I am planning to make little changes this weekend. After that I will make a stable release for this package.

**Comment by tyloo** [comment]
By the time, it's passing when u set "1.0.x-dev" on the composer.json
Le 15 juil. 2015 11:20, "Sebastian Berć" notifications@github.com a
écrit :

**Comment by tyloo** [comment]
This can be closed... :)
