### ISSUE TITLE
[Feature Request] Make Cache System off for specific request

### ISSUE THREAD

**Issue by tyloo** [SebastianBerc/Repositories#6]
Hello,

I have set the trait ShouldCache for a model on my frontend, but I need to set it off for the backend. It would be great to be able to set the caching off for specific calls.

ex : $repository->noCache()->all();
and the opposite (maybe) :
$repository->cache($tag = null)->all();

What do you think?

**Comment by SebastianBerc** [comment]
It's a good idea. I thought about that some time ago, but at least I forgot to do this. I am going to do this implementation as soon as I can.
