### ISSUE TITLE
[Bug] Criteria and next queries

### ISSUE THREAD

**Issue by MonikaKrudysz** [SebastianBerc/Repositories#8]
Criteria doesn't work at the second and next queries. It is distrubing when I try to get all records from database when using some kind of pagination.
For example:

```
$repository->criteria(new SomeCriteria());
$repository->simpleFetch($page, $perPage, $columns); // Works fine. And then...
$repository->simpleFetch($nextPage, $perPage, $columns); // ...doesn't work.
```

**Comment by SebastianBerc** [comment]
The bug has been fixed in version 1.0.1. 

Cheers.
